spring:
  application.name: Java-GenAI-Course
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:accounttestdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

client-azureopenai-key: ###########
client-azureopenai-endpoint: ############
client-azureopenai-deployment-name: gpt-35-turbo
client-azureopenai-deployment-names:
  amazon.titan-tg1-large,
  gpt-35-turbo,
  cohere.command-text-v14,
  meta.llama3-8b-instruct-v1


qdrant-host: localhost
qdrant-port: 6334
qdrant-collection-name: my-collection
text-embeddings-model-name: text-embedding-ada-002

